---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
knitr::opts_chunk$set(eval = FALSE)
```


# NONMEM toolbox

```{r}
nonmem_toolbox()
```

```{r}
nonmem_toolbox(nonmem_exe = "/opt/nm/run/nmfe74",
               nmcheck_exe = "/opt/nm/tr/NMTRAN.exe")
```

```{r}
nonmem_toolbox(nonmem_exe = "/usr/local/bin/nmr",
               nonmem_call = "{nonmem_exe} -local {control_file}",
               nmcheck_exe = "/usr/local/bin/nmr",
               nmcheck_call = "{nmcheck_exe} -test {control_file}")
```

# NONMEM monitor

## Start runs with NONMEM executable

Set `nonmem_exe` argument to your NONMEM executable path.

```{r}
nonmem_monitor(nonmem_exe = "/opt/nm/run/nmfe74",
               nmcheck_exe = "/opt/nm/tr/NMTRAN.exe",
               nonmem_parafile = "/opt/nm/runfiles/mpilinux8.pnm")
```

## Start runs with PsN

Set `nonmem_exe` argument to your PsN execute command.

```{r}
nonmem_monitor(nonmem_exe = "/usr/local/bin/execute",
               nonmem_call = "{nonmem_exe} {control_file} -nodes={n_nodes}",
               nmcheck_exe = "/opt/nm/tr/NMTRAN.exe")
```

# Dataset exploration

```{r}
dataset_exploration()
```

